### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by zekromy12345678** [bwees/pymarketwatch#2]
when running the example program i encounter an error in line 80 of __init__,py. the error is KeyError: '_csrf' . Any help or suggestions would be appreciated!!!

**Comment by bwees** [comment]
Unfortunately it looks like marketwatch changed the login system :(. I do not have any time to fix this right now. If you would like, you may submit a PR if you are able to fix it (you can reverse engineer everything wi inspect element network tab in chrome). I will archive this in the near future if there is no interest.

Sorry for the inconvenience!

Brandon Wees
